/**
 * Generate blog/*.html, blog/index.html, and update sitemap blog URLs.
 * Source: content/blog/*.md
 */
const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

const root = path.join(__dirname, '..');
const contentDir = path.join(root, 'content', 'blog');
const blogOutDir = path.join(root, 'blog');
const sitemapPath = path.join(root, 'sitemap.xml');

const SITE_URL = 'https://solutions.wildmindai.com';
const INCLUDE_DRAFTS = process.env.INCLUDE_DRAFTS === '1';

marked.setOptions({ gfm: true, breaks: false });

function escapeHtml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDisplayDate(iso) {
  if (!iso) return '';
  const d = new Date(iso + 'T12:00:00');
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

function postUrl(slug) {
  return '/blog/' + slug;
}

function absoluteUrl(pathname) {
  return SITE_URL + pathname;
}

function loadPosts() {
  if (!fs.existsSync(contentDir)) return [];

  return fs.readdirSync(contentDir)
    .filter(function (f) { return f.endsWith('.md'); })
    .map(function (file) {
      const raw = fs.readFileSync(path.join(contentDir, file), 'utf8');
      const parsed = matter(raw);
      return {
        data: parsed.data,
        body: parsed.content,
        file: file
      };
    })
    .filter(function (post) {
      if (!post.data.slug || !post.data.title) {
        console.warn('Skipping invalid post:', post.file);
        return false;
      }
      if (post.data.draft && !INCLUDE_DRAFTS) return false;
      return true;
    })
    .sort(function (a, b) {
      return new Date(b.data.date) - new Date(a.data.date);
    });
}

function renderHeadBlock(options) {
  const o = options;
  return `<!-- Auto-generated by scripts/build-blog.js — edit content/blog/*.md instead -->
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="${escapeHtml(o.description)}" />
<meta name="theme-color" content="#ffffff" />
<!-- SEO: Replace REPLACE_WITH_GSC_VERIFICATION_CODE before deploy. -->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-5MY8YQRD74"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5MY8YQRD74');
</script>
<!-- Google Search Console verification -->
<meta name="google-site-verification" content="REPLACE_WITH_GSC_VERIFICATION_CODE" />
<link rel="canonical" href="${escapeHtml(o.canonical)}" />
<link rel="icon" type="image/png" href="/assets/logos/logo_dark.png" />
<link rel="apple-touch-icon" href="/assets/logos/logo_dark.png" />
<meta property="og:type" content="${escapeHtml(o.ogType || 'website')}" />
<meta property="og:url" content="${escapeHtml(o.canonical)}" />
<meta property="og:title" content="${escapeHtml(o.ogTitle || o.title)}" />
<meta property="og:description" content="${escapeHtml(o.description)}" />
<meta property="og:image" content="${escapeHtml(o.ogImage)}" />
<meta property="og:site_name" content="Wildmind Solutions" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${escapeHtml(o.ogTitle || o.title)}" />
<meta name="twitter:description" content="${escapeHtml(o.description)}" />
<meta name="twitter:image" content="${escapeHtml(o.ogImage)}" />
<title>${escapeHtml(o.pageTitle)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Instrument+Serif:ital@0;1&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/styles.css" />
<link rel="stylesheet" href="/assets/responsive.css" />
<link rel="stylesheet" href="/assets/css/ui-improvements.css" />`;
}

function renderRelated(related) {
  if (!related || !related.length) return '';
  const items = related.map(function (r) {
    return `          <li><a href="${escapeHtml(r.url)}">${escapeHtml(r.label)}</a></li>`;
  }).join('\n');
  return `
      <div class="blog-related">
        <h3>Related reading</h3>
        <ul>
${items}
        </ul>
      </div>`;
}

function renderCallout(callout) {
  if (!callout || !callout.title) return '';
  return `
      <div class="case-callout">
        <div>
          <h4>${escapeHtml(callout.title)}</h4>
          <p>${escapeHtml(callout.text)}</p>
        </div>
        <a href="${escapeHtml(callout.ctaUrl || '/contact')}" class="btn btn-primary">${escapeHtml(callout.ctaLabel || 'Learn more')} <span class="arrow">→</span></a>
      </div>`;
}

function renderPostHtml(post) {
  const d = post.data;
  const slug = d.slug;
  const url = postUrl(slug);
  const canonical = absoluteUrl(url);
  const bodyHtml = marked.parse(post.body);
  const tagsHtml = (d.tags || []).map(function (t) {
    return `<span class="tag">${escapeHtml(t)}</span>`;
  }).join('\n      ');

function renderH1(d) {
  const title = d.title || '';
  const accent = (d.heroAccent || '').trim();
  if (accent && title.includes(accent)) {
    const plain = title.replace(accent, '').trim();
    return `${escapeHtml(plain)} <span class="accent-italic">${escapeHtml(accent)}</span>`;
  }
  return escapeHtml(title);
}

  const keywordsJson = JSON.stringify(d.keywords || []);
  const breadcrumbName = d.breadcrumb || d.title;

  return `<!DOCTYPE html>
<html lang="en">
<head>
${renderHeadBlock({
  description: d.description,
  canonical: canonical,
  ogType: 'article',
  ogTitle: d.title,
  ogImage: absoluteUrl(d.coverImage),
  pageTitle: d.title + ' — Wildmind Solutions',
  title: d.title
})}
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {"@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE_URL}/"},
    {"@type": "ListItem", "position": 2, "name": "Blog", "item": "${SITE_URL}/blog"},
    {"@type": "ListItem", "position": 3, "name": ${JSON.stringify(breadcrumbName)}, "item": "${canonical}"}
  ]
}
</script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": ${JSON.stringify(d.title)},
  "description": ${JSON.stringify(d.description)},
  "datePublished": ${JSON.stringify(d.date)},
  "dateModified": ${JSON.stringify(d.dateModified || d.date)},
  "author": {
    "@type": "Organization",
    "name": "Wildmind Solutions"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Wildmind Solutions",
    "url": "${SITE_URL}"
  },
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "${canonical}"
  },
  "articleSection": ${JSON.stringify(d.articleSection || '')},
  "keywords": ${keywordsJson}
}
</script>
</head>
<body data-page="blog" data-base="">

<div id="nav-slot"></div>

<section class="subhero article-hero">
  <div class="container">
    <nav aria-label="Breadcrumb" class="breadcrumb-nav">
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="/blog">Blog</a></li>
        <li aria-current="page">${escapeHtml(breadcrumbName)}</li>
      </ol>
    </nav>
    <div class="article-tags">
      ${tagsHtml}
    </div>
    <h1>${renderH1(d)}</h1>
    <p class="article-byline">By Wildmind Team · ${formatDisplayDate(d.date)} · ${escapeHtml(d.readTime)}</p>
  </div>
</section>

<section class="article-cover-section">
  <div class="container">
    <figure class="article-cover">
      <img src="${escapeHtml(d.coverImage)}" alt="${escapeHtml(d.coverAlt)}" width="2752" height="1536" loading="eager" decoding="async" />
    </figure>
  </div>
</section>

<section>
  <div class="container">
    <hr class="article-divider">
    <article class="article-body">
${bodyHtml.trim()}
${renderRelated(d.related)}
${renderCallout(d.callout)}
    </article>
  </div>
</section>

<div id="footer-slot"></div>

<script src="/assets/partials.js"></script>
<script src="/assets/main.js"></script>
</body>
</html>
`;
}

function renderBlogCard(post) {
  const d = post.data;
  const cats = (d.categories || []).join(' ');
  const cardExcerpt = d.excerpt || d.description;
  return `      <a href="${postUrl(d.slug)}" class="blog-card" data-filter-target="blog" data-category="${escapeHtml(cats)}">
        <div class="blog-card-visual">
<img src="${escapeHtml(d.coverImage)}" alt="${escapeHtml(d.coverAlt)}" class="blog-card-img" width="2752" height="1536" loading="lazy" decoding="async" />
        </div>
        <div class="blog-card-body">
          <span class="blog-card-tag">${escapeHtml(d.cardTag || (d.tags || []).join(' · '))}</span>
          <h3>${escapeHtml(d.title)}</h3>
          <p>${escapeHtml(cardExcerpt)}</p>
          <div class="blog-card-meta">
            <span>${formatDisplayDate(d.date)}</span>
            <span>${escapeHtml(d.readTime)}</span>
          </div>
        </div>
      </a>`;
}

function renderBlogIndex(posts) {
  const cards = posts.map(renderBlogCard).join('\n\n');
  const canonical = absoluteUrl('/blog');
  const description = 'Insights on AI engineering, enterprise software, and the GCC market from Wildmind Solutions — production-grade engineering from Ahmedabad, India.';

  return `<!DOCTYPE html>
<html lang="en">
<head>
${renderHeadBlock({
  description: description,
  canonical: canonical,
  ogType: 'website',
  ogTitle: 'Blog — Wildmind Solutions',
  ogImage: absoluteUrl('/assets/logos/wildmind_solutions.png'),
  pageTitle: 'Blog — Wildmind Solutions',
  title: 'Blog — Wildmind Solutions'
})}
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {"@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE_URL}/"},
    {"@type": "ListItem", "position": 2, "name": "Blog", "item": "${canonical}"}
  ]
}
</script>
</head>
<body data-page="blog" data-base="">

<div id="nav-slot"></div>

<section class="subhero">
  <div class="container">
    <nav aria-label="Breadcrumb" class="breadcrumb-nav">
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li aria-current="page">Blog</li>
      </ol>
    </nav>
    <span class="section-label">INSIGHTS &AMP; ENGINEERING NOTES</span>
    <h1>Thinking in <span class="accent-italic">production.</span></h1>
    <p>Practical writing on AI engineering, enterprise software, and building for the GCC market — from a team that ships real systems, not slide decks.</p>
  </div>
</section>

<section class="section-tight-top">
  <div class="container">
    <div class="filter-tabs" data-filter-group="blog">
      <button type="button" class="filter-tab is-active" data-filter="all">All</button>
      <button type="button" class="filter-tab" data-filter="ai-engineering">AI Engineering</button>
      <button type="button" class="filter-tab" data-filter="enterprise">Enterprise</button>
      <button type="button" class="filter-tab" data-filter="gcc-market">GCC Market</button>
    </div>

    <div class="blog-grid">
${cards}
    </div>
  </div>
</section>

<section class="cta-section">
  <div class="container">
    <div class="cta-card reveal">
      <span class="section-label">WORK WITH US</span>
      <h2>Ready to move from reading to <span class="accent-italic">building?</span></h2>
      <p>Tell us what you're working on. We respond within one business day — first conversation is free.</p>
      <a href="/contact" class="btn btn-primary">
        Start a conversation
        <span class="arrow">→</span>
      </a>
    </div>
  </div>
</section>

<div id="footer-slot"></div>

<script src="/assets/partials.js"></script>
<script src="/assets/main.js"></script>
</body>
</html>
`;
}

function updateSitemap(posts) {
  if (!fs.existsSync(sitemapPath)) {
    console.warn('sitemap.xml not found, skipping');
    return;
  }

  let xml = fs.readFileSync(sitemapPath, 'utf8');

  xml = xml.replace(/\s*<url>\s*<loc>https:\/\/solutions\.wildmindai\.com\/blog\/[^<]+<\/loc>[\s\S]*?<\/url>/g, '');

  const blogEntries = [];
  const today = new Date().toISOString().slice(0, 10);

  blogEntries.push(`  <url>
    <loc>${absoluteUrl('/blog')}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>`);

  posts.forEach(function (post) {
    const mod = post.data.dateModified || post.data.date || today;
    blogEntries.push(`  <url>
    <loc>${absoluteUrl(postUrl(post.data.slug))}</loc>
    <lastmod>${mod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>`);
  });

  xml = xml.replace('</urlset>', blogEntries.join('\n') + '\n</urlset>');
  fs.writeFileSync(sitemapPath, xml, 'utf8');
  console.log('Updated sitemap.xml with', posts.length + 1, 'blog URLs');
}

function main() {
  const posts = loadPosts();
  console.log('Building', posts.length, 'blog post(s)...');

  if (!fs.existsSync(blogOutDir)) {
    fs.mkdirSync(blogOutDir, { recursive: true });
  }

  const activeSlugs = new Set(posts.map(function (p) { return p.data.slug; }));

  fs.readdirSync(blogOutDir).forEach(function (file) {
    if (!file.endsWith('.html') || file === 'index.html') return;
    const slug = file.replace(/\.html$/, '');
    if (!activeSlugs.has(slug)) {
      fs.unlinkSync(path.join(blogOutDir, file));
      console.log('Removed stale', file);
    }
  });

  posts.forEach(function (post) {
    const outPath = path.join(blogOutDir, post.data.slug + '.html');
    fs.writeFileSync(outPath, renderPostHtml(post), 'utf8');
    console.log('Wrote', outPath);
  });

  fs.writeFileSync(path.join(blogOutDir, 'index.html'), renderBlogIndex(posts), 'utf8');
  console.log('Wrote blog/index.html');

  updateSitemap(posts);
}

main();
